CREATE DATABASE BBANK

USE BBANK


CREATE TABLE KLIENT

(KLIENT_NUM_KLIENTA INTEGER PRIMARY KEY,
KLIENT_FIO VARCHAR(20) NOT NULL,
KLIENT_NOM_PASPORTA INTEGER NOT NULL,
KLIENT_ADRES VARCHAR(20)NOT NULL,
KLIENT_TELEFON VARCHAR(20)NOT NULL,
KLIENT_MESTO_RAB VARCHAR(10)NOT NULL,
KLIENT_PLATA INTEGER NOT NULL,
);
CREATE TABLE SOTRUD
(SOTRUD_NUM_SOTRUD INTEGER PRIMARY KEY,
SOTRUD_FIO_SOTRUD VARCHAR(20)NOT NULL,
SOTRUD_DOLZNOST VARCHAR(15)NOT NULL

);

CREATE TABLE KREDITS
(KREDIT_NUM_KREDIT INTEGER PRIMARY KEY,
KREDIT_TIP VARCHAR(20)NOT NULL,
KREDIT_PROC_STAV NUMERIC(3)NOT NULL,

);
CREATE TABLE DOGOVOR
(DOGOVOR_NOM_DOGOVORA INTEGER PRIMARY KEY,
DOGOVOR_DATA_DOGOVORA DATETIME,
DOGOVOR_TIP_DOOVORA VARCHAR(10)NOT NULL,
KLIENT_NUM_KLIENTA INTEGER,
SOTRUD_NUM_SOTRUD INTEGER,
KREDIT_NUM_KREDIT INTEGER,
CONSTRAINT GT_DOGOVOR FOREIGN KEY(KLIENT_NUM_KLIENTA)
REFERENCES KLIENT(KLIENT_NUM_KLIENTA),
CONSTRAINT GT1_DOGOVOR FOREIGN KEY(SOTRUD_NUM_SOTRUD)
REFERENCES SOTRUD(SOTRUD_NUM_SOTRUD),
CONSTRAINT GT2_DOGOVOR FOREIGN KEY(KREDIT_NUM_KREDIT)
REFERENCES KREDITS(KREDIT_NUM_KREDIT)
);



INSERT INTO KLIENT(KLIENT_NUM_KLIENTA,KLIENT_FIO,KLIENT_NOM_PASPORTA,KLIENT_ADRES,KLIENT_TELEFON,KLIENT_MESTO_RAB,KLIENT_PLATA) VALUES (1,'Мельников Артём ',123432,
'Ленина 17б','43324345', 'ТК Брозекс',30000);
INSERT INTO KLIENT(KLIENT_NUM_KLIENTA,KLIENT_FIO,KLIENT_NOM_PASPORTA,KLIENT_ADRES,KLIENT_TELEFON,KLIENT_MESTO_RAB,KLIENT_PLATA) VALUES (2,'Иванов Евегений ',3459787,
'Щербакова 123','4342314', 'МВД России',55000);
INSERT INTO KLIENT(KLIENT_NUM_KLIENTA,KLIENT_FIO,KLIENT_NOM_PASPORTA,KLIENT_ADRES,KLIENT_TELEFON,KLIENT_MESTO_RAB,KLIENT_PLATA) VALUES (3,'Масленников Юрий ',312453,
'Восточная 17', '433685', 'Авто-лада',40000);
INSERT INTO KLIENT(KLIENT_NUM_KLIENTA,KLIENT_FIO,KLIENT_NOM_PASPORTA,KLIENT_ADRES,KLIENT_TELEFON,KLIENT_MESTO_RAB,KLIENT_PLATA) VALUES (4,'Мальцева Анастасия ',57567,
'Лесная 92', '433452',' клиника',50000);
INSERT INTO KLIENT(KLIENT_NUM_KLIENTA,KLIENT_FIO,KLIENT_NOM_PASPORTA,KLIENT_ADRES,KLIENT_TELEFON,KLIENT_MESTO_RAB,KLIENT_PLATA) VALUES (5,'Бойка Виктор',42352,
'Солнечная 89','4354234', 'ДЮСШ',35000);

INSERT INTO SOTRUD(SOTRUD_NUM_SOTRUD,SOTRUD_FIO_SOTRUD,SOTRUD_DOLZNOST) VALUES (1,'Остапьев Илья','Кредитор')
INSERT INTO SOTRUD(SOTRUD_NUM_SOTRUD,SOTRUD_FIO_SOTRUD,SOTRUD_DOLZNOST) VALUES (2,'Попугай	Кеша','Банкир')
INSERT INTO SOTRUD(SOTRUD_NUM_SOTRUD,SOTRUD_FIO_SOTRUD,SOTRUD_DOLZNOST) VALUES (3,'Петров Степан','Менеждер')

INSERT INTO KREDITS(KREDIT_NUM_KREDIT,KREDIT_PROC_STAV,KREDIT_TIP) VALUES (11,15,'Ипотека')
INSERT INTO KREDITS(KREDIT_NUM_KREDIT,KREDIT_PROC_STAV,KREDIT_TIP) VALUES (12,19,'Потребительский')
INSERT INTO KREDITS(KREDIT_NUM_KREDIT,KREDIT_PROC_STAV,KREDIT_TIP) VALUES (13,16,'Автокредит');

INSERT INTO DOGOVOR (DOGOVOR_NOM_DOGOVORA,DOGOVOR_DATA_DOGOVORA,DOGOVOR_TIP_DOOVORA,KLIENT_NUM_KLIENTA,SOTRUD_NUM_SOTRUD)
VALUES(111,'21.12.2009','Целевой',1,1)
INSERT INTO DOGOVOR (DOGOVOR_NOM_DOGOVORA,DOGOVOR_DATA_DOGOVORA,DOGOVOR_TIP_DOOVORA,KLIENT_NUM_KLIENTA,SOTRUD_NUM_SOTRUD)
VALUES(121,'16.03.2020','НЦелевой',2,2)
INSERT INTO DOGOVOR (DOGOVOR_NOM_DOGOVORA,DOGOVOR_DATA_DOGOVORA,DOGOVOR_TIP_DOOVORA,KLIENT_NUM_KLIENTA,SOTRUD_NUM_SOTRUD)
VALUES(131,'11.12.2017','Целевой',3,3)

Select * from KLIENT
Select * from SOTRUD
Select * from KREDITS
Select * from DOGOVOR

Select DISTINCT KLIENT.KLIENT_FIO,KLIENT.KLIENT_ADRES,KREDITS.KREDIT_PROC_STAV from KLIENT,KREDITS WHERE KREDIT_PROC_STAV>15 and KLIENT_PLATA>50000 GROUP BY KLIENT_FIO,KLIENT_ADRES,KREDIT_PROC_STAV
Select DISTINCT KLIENT.KLIENT_FIO,DOGOVOR.DOGOVOR_DATA_DOGOVORA from KLIENT,DOGOVOR where DOGOVOR_DATA_DOGOVORA>'2010.01.01' GROUP BY  KLIENT.KLIENT_FIO,DOGOVOR.DOGOVOR_DATA_DOGOVORA
Select DISTINCT KLIENT.KLIENT_FIO,KREDITS.KREDIT_TIP from KLIENT,KREDITS where KREDIT_TIP='Автокредит' and KLIENT_PLATA>50000 group By KLIENT_FIO,KREDIT_TIP
